version: "3.8"
services:
  db_client1:
    image: postgres:16.0-alpine
    restart: always
    environment:
      - POSTGRES_DB=client1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "15432:5432"
    volumes:
      - db_client1:/var/lib/postgresql/data_16
  db_client2:
    image: postgres:16.0-alpine
    restart: always
    environment:
      - POSTGRES_DB=client2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "25432:5432"
    volumes:
      - db_client2:/var/lib/postgresql/data_16

volumes:
  db_client1:
    driver: local
  db_client2:
    driver: local
